version: '3.8'

services:
  api:
    build: .  
    ports:
      - "3000:3000"  
    env_file:
      - .env  
    depends_on:
      - db  

  db:
    image: mysql:8.0  
    restart: always  
    env_file:
      - .env  
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"  
    volumes:
      - mysql-data:/var/lib/mysql 

volumes:
  mysql-data: