version: "3.9"

services:
  api:
    build: .  
    container_name: api-onepiece
    ports:
      - "3000:3000"  
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root123
      DB_DATABASE: one_piece_db
      DB_PORT: 3306
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: mysql:8.0  
    container_name: mysql-onepiece
    restart: always  
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: one_piece_db
    ports:
      - "3306:3306"  
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/config/init.sql:/docker-entrypoint-initdb.d/init.sql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:
